AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Specification template describing your function.
Resources:
  postImages:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://serverless-app-sam/7da2aa8cc7688fa79fa536dafe3645a4
      Handler: post-images.lambda_handler
      Runtime: python3.6
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: arn:aws:iam::618448440758:role/lambda-dynamodb-access
      Environment:
        Variables:
          BUCKET_NAME: serverless-app-photos-vue
          TABLE_NAME: photos
      Events:
        Api:
          Type: Api
          Properties:
            Path: /images
            Method: post
  updateImage:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://serverless-app-sam/19f7a2329dec8282d531cb204dbbc22a
      Handler: update-image.lambda_handler
      Runtime: python3.6
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: arn:aws:iam::618448440758:role/lambda-dynamodb-access
      Environment:
        Variables:
          BUCKET_NAME: serverless-app-photos-vue
          TABLE_NAME: photos
      Events:
        Api:
          Type: Api
          Properties:
            Path: /images
            Method: put
  getImages:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://serverless-app-sam/35f5468d66770f4c01bb071967e04d8e
      Handler: get-images.lambda_handler
      Runtime: python3.6
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: arn:aws:iam::618448440758:role/lambda-dynamodb-access
      Environment:
        Variables:
          BUCKET_NAME: serverless-app-photos-vue
          TABLE_NAME: photos
      Events:
        Api:
          Type: Api
          Properties:
            Path: /images
            Method: get
  getImageById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://serverless-app-sam/27251e16b8a788968082cd97701df9a2
      Handler: get-image-by-id.lambda_handler
      Runtime: python3.6
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: arn:aws:iam::618448440758:role/lambda-dynamodb-access
      Environment:
        Variables:
          BUCKET_NAME: serverless-app-photos-vue
          TABLE_NAME: photos
      Events:
        Api:
          Type: Api
          Properties:
            Path: /images/{id}
            Method: get
  deleteImageById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://serverless-app-sam/19da28017a86a7789d36c98e459014ff
      Handler: delete-image-by-id.lambda_handler
      Runtime: python3.6
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: arn:aws:iam::618448440758:role/lambda-dynamodb-access
      Environment:
        Variables:
          BUCKET_NAME: serverless-app-photos-vue
          TABLE_NAME: photos
      Events:
        Api:
          Type: Api
          Properties:
            Path: /images/{id}
            Method: delete
