AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
    postImages:
        Type: 'AWS::Serverless::Function'
        Properties:
            CodeUri: getImages/
            Handler: get-images.lambda_handler
            Runtime: python3.6
            Description: ''
            MemorySize: 128
            Timeout: 15
            Role: arn:aws:iam::618448440758:role/lambda-dynamodb-access
            Environment:
                Variables:
                    BUCKET_NAME: serverless-app-photos-vue
                    TABLE_NAME: photos
            Events:
                Api:
                    Type: Api
                    Properties:
                        Path: /images
                        Method: get
